
spring:
  application:
    name: rpc-feign
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8083

feign:
  client:
    config:
      # 默认日志,   开启日志框架的debug级别
      default:
        loggerLevel: FULL
      # 指定微服务日子级别
      rpc-provider:
        loggerLevel: HEADERS
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50